# Generated by Django 5.0.6 on 2024-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('Desc', models.CharField(max_length=250)),
            ],
        ),
    ]
